language: python
python:
  - "3.2"
  - "3.3"
install:
  - pip install -r requirements.txt
  - python setup.py
script:
  - nosetests
notifications:
  hipchat:
    secure: "CPPF2kVbOuEouvF00MqFWPGFZIWMjpo8wpfFNtiwZn0EQeBDBBaPCHID9YysIBzgC7+fgkIRrSFOwZUIThpI2ex721fCE4MJyKiwthM+MRR5/sKFCytpvPCGTVpv+1i/R5X0kEaJzDDj/KXkPI4ZXwNXov/kDBVYfXF4vCtBoUc="

